### ISSUE TITLE
ResponseHeaderModifier does not permit to set a content with commas

### ISSUE THREAD

**Issue by saez0pub** [envoyproxy/gateway#5733]
*Description*:
>I cannot set `Cache-Control: foo,bar` with ResponseHeaderModifier

*Repro steps*:

1. Deploy the quickstart example
2. Apply the following HTTPRoute:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  hostnames:
  - www.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: backend
      port: 3000
      weight: 1
    filters:
    - responseHeaderModifier:
        set:
        - name: Cache-Control
          value: private, no-store
      type: ResponseHeaderModifier
    matches:
    - path:
        type: PathPrefix
        value: /
```

3. Run the following curl command:

curl -i http://${ENVOY_GATEWAY_IP}/-H 'Host: www.example.com' -H 'X-Echo-Set-Header: Cache-control: value1' | grep ^cache-control
You will see This:
```
cache-control:  no-store
```

Expected output:
```
cache-control: private, no-store
```

Proxy config extract:
```
          "response_headers_to_add": [
           {
            "header": {
             "key": "Cache-Control",
             "value": "private"
            },
            "append_action": "OVERWRITE_IF_EXISTS_OR_ADD"
           },
           {
            "header": {
             "key": "Cache-Control",
             "value": " no-store"
            },
            "append_action": "OVERWRITE_IF_EXISTS_OR_ADD"
           }
          ],
```

**Comment by saez0pub** [comment]
Seems linked to #4031

I'm kinda puzzled about this: https://gateway-api.sigs.k8s.io/reference/spec/#httpheaderfilter
> Configuration to set or add multiple values for a header must use RFC 7230 header value formatting, separating each value with a comma.

If I look at the RFC, it says
> A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

I think the specification was talking more about the former which is more of a comma-separated join than generating an array of values from a comma-separated list.

Writing a test for this part https://github.com/envoyproxy/gateway/pull/4031/files#diff-698fcb61202958faff1d63f1eed4a0a3111a888e3b7370f8f16a32cd96b78349R453 might show the bug I'm running into.

**Comment by arkodg** [comment]
cc @liorokman

**Comment by arkodg** [comment]
this was fixed in https://github.com/envoyproxy/gateway/issues/4023, is this a regression ?

**Comment by patrostkowski** [comment]
@arkodg not fixed, the configuration still returns multiple headers with one value

**Comment by arkodg** [comment]
thanks @patrostkowski looks like is was never tested for responseHeaderModifier, please follow #4023 to add similar test cases

**Comment by arkodg** [comment]
still working on this one @patrostkowski ?

**Comment by VonNao** [comment]
Is this issue still worked on or fixed?

**Comment by kkk777-7** [comment]
I’ve opened a PR to address this issue. Please take a look when you have a moment.
