### ISSUE TITLE
How to tell which upstream (primary vs fallback) is serving/failing via metrics in Envoy Gateway?

### ISSUE THREAD

**Issue by mnasruul** [envoyproxy/gateway#6918]
*Description*:
# Setup:
 Envoy Gateway + Gateway API.
 One HTTPRoute pointing to two Backend resources:
 backend-primary (SD-WAN path)
 backend-fallback (FRP path) with fallback: true
 Metrics exported via OTLP → OpenTelemetry Collector → New Relic.
# What I can see today:
 I do get cluster-level metrics like cluster.membership_healthy and cluster.membership_total.
 envoy.cluster_name looks like: httproute/<ns>/<route-name>/rule/<idx>.
 When I intentionally break the primary path (firewall drop), the route’s Healthy % drops (<100%), so failover is clearly happening.
# What I cannot tell (yet):
 Which upstream is actually failing (primary vs fallback)?
 Is there a way, via OTLP metrics, to get either:
 per-priority health (e.g., P0=primary, P1=fallback) — metric names like cluster.priority.membership_healthy? and the attribute key that carries the priority?
 per-endpoint/host labels (e.g., an attribute for the upstream address) so I can facet by the actual upstream host?
# Questions:
-  Does Envoy Gateway (with the OTLP metrics sink) expose per-priority or per-host health out of the box? If yes, what are the exact metric names and attribute keys I should look for?
- If OTLP doesn’t carry that granularity, is the recommended approach to scrape /stats/prometheus from the data plane (to get labels like envoy_upstream_address) and forward those via the Collector?
-  Any other best practices to reliably detect “primary down, traffic on fallback” using metrics (instead of relying solely on access logs with %UPSTREAM_HOST%)?

```
# HTTPRoute
 spec:
   rules:
     - backendRefs:
         - group: gateway.envoyproxy.io
           kind: Backend
           name: backend-primary
           port: 8080
         - group: gateway.envoyproxy.io
           kind: Backend
           name: backend-fallback
           port: 80
       # fallback is set on the Backend resource:
 ---
 # Backend (primary)
 spec:
   endpoints:
     - ip:
         address: 10.0.0.1
         port: 8080
 ---
 # Backend (fallback)
 spec:
   fallback: true
   endpoints:
     - ip:
         address: 10.0.0.2
         port: 80
```

Any pointers (metric names/attributes or config knobs) would be super appreciated. Thanks!

**Comment by arkodg** [comment]
@mnasruul you could enable per endpoint metrics, at the cost of consuming more memory
https://gateway.envoyproxy.io/docs/api/extension_types/#proxymetrics

**Comment by mnasruul** [comment]
@arkodg Thanks, i will check it

**Comment by mnasruul** [comment]
I have enabled per-endpoint metrics and explored this feature. The metric `envoy_cluster_endpoint_healthy` at Prometheus or `cluster.endpoint.healthy` on New Relic via OpenTelemetry gives me what I need, so this issue is resolved. Thanks a lot!

**Comment by kivra-ahmwar** [comment]
@mnasruul Did you need to do anything else for the metric to pop up? I still can't see the envoy_cluster_endpoint_healthy after adding this `envoyProxy.spec.telemetry.metrics.enablePerEndpointStats: true`. I restarated the daemonsets and the envoy-gateway deployment. Whenever i curl my envoy pods and grep for the metric name i get nothing.
`curl <envoy-pod-ip>:19001/stats/prometheus | grep envoy_cluster_endpoint`

**Comment by mnasruul** [comment]
This feature is enable at version https://gateway.envoyproxy.io/news/releases/notes/v1.1.0/ `Added Support for Per-Endpoint stats in EnvoyProxy CRD,` please check you envoy gateway version

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-name-envoy-proxy
spec:
  telemetry:
    metrics:
      sinks:
        - type: OpenTelemetry
          openTelemetry:
            host: otel-collector.monitoring.svc.cluster.local
            port: 4317
      enablePerEndpointStats: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: custom-name-envoy-proxy
```

**Comment by kivra-ahmwar** [comment]
Im running version 1.5. I have the EnvoyProxy attached to the GatewayClass and then i refer to the GatewayClass from the Gateway. It works with other configuration changes i do to the EnvoyProxy, but for some reason it doesnt work with this.

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: internal-eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: eg-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: eg-config
spec:
  mergeGateways: true
  telemetry:
    metrics:
      enablePerEndpointStats: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gw
spec:
  gatewayClassName: internal-eg
```

**Comment by kivra-ahmwar** [comment]
Wait, i just realized i forgot the sink...

**Comment by mnasruul** [comment]
What about the CRD EnvoyProxy? I started using Envoy Gateway version 1.0 and Upgraded to 1.5 with helm. After the upgrade the CRD still version 1.0 and i had to update it manually. To verify, please check with command `kubectl explain envoyproxy.spec.telemetry.metrics`
